<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class MunicipioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $municipios = [
            //Amazonas
            ['nombre' => 'ALTO ORINOCO', 'estados_id' => 2],
            ['nombre' => 'ATABAPO', 'estados_id' => 2],
            ['nombre' => 'ATURES', 'estados_id' => 2],
            ['nombre' => 'MANAPIARE', 'estados_id' => 2],
            ['nombre' => 'MAROA', 'estados_id' => 2],
            ['nombre' => 'RIO NEGRO', 'estados_id' => 2],
            //Anzoategui
            ['nombre' => 'ANACO', 'estado_id' => 3],
            ['nombre' => 'ARAGUA', 'estado_id' => 3],
            ['nombre' => 'DIEGO BAUTISTA URBANEJA', 'estado_id' => 3],
            ['nombre' => 'FERNANDOPENAVER', 'estado_id' => 3],
            ['nombre' => 'FRANCISCO DEL CARMEN CARVAJAL' , 'estado_id' => 3],
            ['nombre' => 'FRANCISCO DE MIRANDA' , 'estado_id' => 3],
            ['nombre' => 'GUANTA' , 'estado_id' => 3],
            ['nombre' => 'INDEPENDENCIA' , 'estado_id' => 3],
            ['nombre' => 'JOSE GREGORIO MONAGAS' , 'estado_id' => 3],
            ['nombre' => 'JUAN ANTONIO SOTILLO' , 'estado_id' => 3],
            ['nombre' => 'JUAN MANUEL CAJIGAL' , 'estado_id' => 3],
            ['nombre' => 'LIBERTAD' , 'estado_id' => 3],
            ['nombre' => 'MANUEL EZEQUIEL BRUZUAL' , 'estado_id' => 3],
            ['nombre' => 'PEDRO MARIA FREITES' , 'estado_id' => 3],
            ['nombre' => 'PIRITU' , 'estado_id' => 3],
            ['nombre' => 'SAN JOSE DE GUANIPA' , 'estado_id' => 3],
            ['nombre' => 'SAN JUAN DE CAPISTRANO' , 'estado_id' => 3],
            ['nombre' => 'SANTA ANA' , 'estado_id' => 3],
            ['nombre' => 'SIMON BOLIVAR' , 'estado_id' => 3],
            ['nombre' => 'SIMON RODRIGUEZ' , 'estado_id' => 3],
            ['nombre' => 'GENERAL SIR ARTHUR MCGREGOR' , 'estado_id' => 3],
            //Apure
            ['nombre' => 'ACHAGUAS' , 'estado_id' => 4],
            ['nombre' => 'BIRUACA' , 'estado_id' => 4],
            ['nombre' => 'MUÑOZ' , 'estado_id' => 4],
            ['nombre' => 'PEDRO CAMEJO' , 'estado_id' => 4],
            ['nombre' => 'SAN FERNANDO' , 'estado_id' => 4],
            ['nombre' => 'PAEZ' , 'estado_id' => 4],
            ['nombre' => 'ROMULO GALLEGOS' , 'estado_id' => 4],
            //Aragua
            ['nombre' => 'BOLIVAR' , 'estado_id' => 5],
            ['nombre' => 'CAMATAGUA' , 'estado_id' => 5],
            ['nombre' => 'FRANCISCO LINARES ALCÁNTARA' , 'estado_id' => 5],
            ['nombre' => 'ATANASIO GIRARDOT' , 'estado_id' => 5],
            ['nombre' => 'JOSÉ ANGEL LAMAS' , 'estado_id' => 5],
            ['nombre' => 'JOSÉ FELIZ RIVAS' , 'estado_id' => 5],
            ['nombre' => 'JOSÉ RAFAEL REVENGA' , 'estado_id' => 5],
            ['nombre' => 'LIBERTADOR' , 'estado_id' => 5],
            ['nombre' => 'MARIO BRICEÑO IRAGORRY' , 'estado_id' => 5],
            ['nombre' => 'OCUMARE DE LA COSTA DE ORO' , 'estado_id' => 5],
            ['nombre' => 'SAN CASIMIRO' , 'estado_id' => 5],
            ['nombre' => 'SAN SEBASTIÁN' , 'estado_id' => 5],
            ['nombre' => 'SANTIAGO MARIÑO' , 'estado_id' => 5],
            ['nombre' => 'SANTOS MICHELENA' , 'estado_id' => 5],
            ['nombre' => 'SUCRE' , 'estado_id' => 5],
            ['nombre' => 'TOVAR' , 'estado_id' => 5],
            ['nombre' => 'URDANETA' , 'estado_id' => 5],
            ['nombre' => 'ZAMORA' , 'estado_id' => 5],
            //Barinas
            ['nombre' => 'ALBERTO ARVELO TORREALBA' , 'estado_id' => 6],
            ['nombre' => 'ANDRÉS ELOY BLANCO' , 'estado_id' => 6],
            ['nombre' => 'ANTONIO JOSÉ DE SUCRE' , 'estado_id' => 6],
            ['nombre' => 'ARISMENDI' , 'estado_id' => 6],
            ['nombre' => 'BARINAS' , 'estado_id' => 6],
            ['nombre' => 'BOLIVAR' , 'estado_id' => 6],
            ['nombre' => 'CRUZ PAREDES' , 'estado_id' => 6],
            ['nombre' => 'EZEQUIEL ZAMORA' , 'estado_id' => 6],
            ['nombre' => 'OBISPOS' , 'estado_id' => 6],
            ['nombre' => 'PEDRAZA' , 'estado_id' => 6],
            ['nombre' => 'ROJAS' , 'estado_id' => 6],
            ['nombre' => 'SOSA' , 'estado_id' => 6],
            //Bolivar
            ['nombre' => 'CARONÍ' , 'estado_id' => 7],
            ['nombre' => 'CEDEÑO' , 'estado_id' => 7],
            ['nombre' => 'EL CALLAO' , 'estado_id' => 7],
            ['nombre' => 'GRAN SABANA' , 'estado_id' => 7],
            ['nombre' => 'HERES' , 'estado_id' => 7],
            ['nombre' => 'PADRE PEDRO CHIEN' , 'estado_id' => 7],
            ['nombre' => 'PIAR' , 'estado_id' => 7],
            ['nombre' => 'ANGOSTURA RAÚL LEONI' , 'estado_id' => 7],
            ['nombre' => 'ROSCIO' , 'estado_id' => 7],
            ['nombre' => 'SIFONTES' , 'estado_id' => 7],
            ['nombre' => 'SUCRE' , 'estado_id' => 7],
            //Carabobo
            ['nombre' => 'BEJUMA' , 'estado_id' => 8],
            ['nombre' => 'CARLOS ARVELO' , 'estado_id' => 8],
            ['nombre' => 'DIEGO IBARRA' , 'estado_id' => 8],
            ['nombre' => 'GUACARA' , 'estado_id' => 8],
            ['nombre' => 'JUAN JOSÉ MORA' , 'estado_id' => 8],
            ['nombre' => 'LIBERTADOR' , 'estado_id' => 8],
            ['nombre' => 'LOS GUAYOS' , 'estado_id' => 8],
            ['nombre' => 'MIRANDA' , 'estado_id' => 8],
            ['nombre' => 'MONTALBÁN' , 'estado_id' => 8],
            ['nombre' => 'NAGUANAGUA' , 'estado_id' => 8],
            ['nombre' => 'PUERTO CABELLO' , 'estado_id' => 8],
            ['nombre' => 'SAN DIEGO' , 'estado_id' => 8],
            ['nombre' => 'SAN JOAQUÍN' , 'estado_id' => 8],
            ['nombre' => 'VALENCIA' , 'estado_id' => 8],
            //Cojedes
            ['nombre' => 'ANZOÁTEGUI' , 'estado_id' => 9],
            ['nombre' => 'PAO DE SAN JUAN BAUTISTA' , 'estado_id' => 9],
            ['nombre' => 'TINAQUILLO' , 'estado_id' => 9],
            ['nombre' => 'GIRARDOT' , 'estado_id' => 9],
            ['nombre' => 'LIMA BLANCO' , 'estado_id' => 9],
            ['nombre' => 'RICAURTE' , 'estado_id' => 9],
            ['nombre' => 'RÓMULO GALLEGOS' , 'estado_id' => 9],
            ['nombre' => 'SAN CARLOS' , 'estado_id' => 9],
            ['nombre' => 'TINACO' , 'estado_id' => 9],
            //Delta Amacuro
            ['nombre' => 'ANTONIO DÍAZ' , 'estado_id' => 10],
            ['nombre' => 'CASACOIMA' , 'estado_id' => 10],
            ['nombre' => 'PEDERNALES' , 'estado_id' => 10],
            ['nombre' => 'TUCUPITA' , 'estado_id' => 10],
            //Districto Capital
            ['nombre' => 'LIBERTADOR' , 'estado_id' => 11],
            //Falcón
            ['nombre' => 'ACOSTA', 'estado_id' => 12],
            ['nombre' => 'BOLÍVAR', 'estado_id' => 12],
            ['nombre' => 'BUCHIVACOA', 'estado_id' => 12],
            ['nombre' => 'CACIQUE MANAURE', 'estado_id' => 12],
            ['nombre' => 'CARIRUBANA', 'estado_id' => 12],
            ['nombre' => 'COLINA', 'estado_id' => 12],
            ['nombre' => 'DABAJURO', 'estado_id' => 12],
            ['nombre' => 'DEMOCRACIA', 'estado_id' => 12],
            ['nombre' => 'FALCÓN', 'estado_id' => 12],
            ['nombre' => 'FEDERACIÓN', 'estado_id' => 12],
            ['nombre' => 'JACURA', 'estado_id' => 12],
            ['nombre' => 'LOS TAQUES', 'estado_id' => 12],
            ['nombre' => 'MAUROA', 'estado_id' => 12],
            ['nombre' => 'MIRANDA', 'estado_id' => 12],
            ['nombre' => 'MONSEÑOR ITURRIZA', 'estado_id' => 12],
            ['nombre' => 'PALMASOLA', 'estado_id' => 12],
            ['nombre' => 'PETIT', 'estado_id' => 12],
            ['nombre' => 'PÍRITU', 'estado_id' => 12],
            ['nombre' => 'SAN FRANCISCO', 'estado_id' => 12],
            ['nombre' => 'JOSÉ LAURENCIO SILVA', 'estado_id' => 12],
            ['nombre' => 'SUCRE', 'estado_id' => 12],
            ['nombre' => 'TOCÓPERO', 'estado_id' => 12],
            ['nombre' => 'UNIÓN', 'estado_id' => 12],
            ['nombre' => 'URUMACO', 'estado_id' => 12],
            ['nombre' => 'ZAMORA', 'estado_id' => 12],
            //Guárico
            ['nombre' => 'CAMAGUÁN', 'estado_id' => 13],
            ['nombre' => 'CHAGUARAMAS', 'estado_id' => 13],
            ['nombre' => 'EL SOCORRO', 'estado_id' => 13],
            ['nombre' => 'SEBASTIÁN FRANCISCO DE MIRANDA', 'estado_id' => 13],
            ['nombre' => 'JOSÉ FÉLIX RIBAS', 'estado_id' => 13],
            ['nombre' => 'JOSÉ TADEO MONAGAS', 'estado_id' => 13],
            ['nombre' => 'JUAN GERMÁN ROSCIO', 'estado_id' => 13],
            ['nombre' => 'JULIÁN MELLADO', 'estado_id' => 13],
            ['nombre' => 'LAS MERCEDES', 'estado_id' => 13],
            ['nombre' => 'LEONARDO INFANTE', 'estado_id' => 13],
            ['nombre' => 'ORTIZ', 'estado_id' => 13],
            ['nombre' => 'PEDRO ZARAZA', 'estado_id' => 13],
            ['nombre' => 'SAN GERÓNIMO DE GUAYABAL', 'estado_id' => 13],
            ['nombre' => 'SAN JOSÉ DE GUARIBE', 'estado_id' => 13],
            ['nombre' => 'SANTA MARÍA DE IPIRE', 'estado_id' => 13],
            //Lara
            ['nombre' => 'ANDRÉS ELOY BLANCO', 'estado_id' => 14],
            ['nombre' => 'CRESPO', 'estado_id' => 14],
            ['nombre' => 'MORÁN', 'estado_id' => 14],
            ['nombre' => 'PALAVECINO', 'estado_id' => 14],
            ['nombre' => 'SIMÓN PLANAS', 'estado_id' => 14],
            ['nombre' => 'TORRES', 'estado_id' => 14],
            ['nombre' => 'URDANETA', 'estado_id' => 14],
            ['nombre' => 'IRIBARREN', 'estado_id' => 14],
            ['nombre' => 'JIMÉNEZ', 'estado_id' => 14],
            //La Guaira
            ['nombre' => 'VARGAS', 'estado_id' => 15],
            //Mérida
            ['nombre' => 'ALBERTO ADRIANI', 'estado_id' => 16],
            ['nombre' => 'ANTONIO PINTO SALINAS', 'estado_id' => 16],
            ['nombre' => 'ANDRÉS BELLO', 'estado_id' => 16],
            ['nombre' => 'ARICAGUA', 'estado_id' => 16],
            ['nombre' => 'ARZOBISPO CHACÓN', 'estado_id' => 16],
            ['nombre' => 'CAMPO ELÍAS', 'estado_id' => 16],
            ['nombre' => 'CARACCIOLO PARRA OLMEDO', 'estado_id' => 16],
            ['nombre' => 'CARDENAL QUINTERO', 'estado_id' => 16],
            ['nombre' => 'GUARAQUE', 'estado_id' => 16],
            ['nombre' => 'JULIO CÉSAR SALAS', 'estado_id' => 16],
            ['nombre' => 'JUSTO BRICEÑO', 'estado_id' => 16],
            ['nombre' => 'LIBERTADOR', 'estado_id' => 16],
            ['nombre' => 'MIRANDA', 'estado_id' => 16],
            ['nombre' => 'OBISPO RAMOS DE LORA', 'estado_id' => 16],
            ['nombre' => 'PADRE NOGUERA', 'estado_id' => 16],
            ['nombre' => 'PUEBLO LLANO', 'estado_id' => 16],
            ['nombre' => 'RANGEL', 'estado_id' => 16],
            ['nombre' => 'RIVAS DÁVILA', 'estado_id' => 16],
            ['nombre' => 'SANTOS MARQUINA', 'estado_id' => 16],
            ['nombre' => 'SUCRE', 'estado_id' => 16],
            ['nombre' => 'TOVAR', 'estado_id' => 16],
            ['nombre' => 'TULIO FEBRES CORDERO', 'estado_id' => 16],
            ['nombre' => 'ZEA', 'estado_id' => 16],
            //Miranda
            ['nombre' => 'ACEVEDO', 'estado_id' => 17],
            ['nombre' => 'ANDRÉS BELLO', 'estado_id' => 17],
            ['nombre' => 'BARUTA', 'estado_id' => 17],
            ['nombre' => 'BRIÓN', 'estado_id' => 17],
            ['nombre' => 'BUROZ', 'estado_id' => 17],
            ['nombre' => 'CARRIZAL', 'estado_id' => 17],
            ['nombre' => 'CHACAO', 'estado_id' => 17],
            ['nombre' => 'CRISTÓBAL ROJAS', 'estado_id' => 17],
            ['nombre' => 'EL HATILLO', 'estado_id' => 17],
            ['nombre' => 'GUAICAIPURO', 'estado_id' => 17],
            ['nombre' => 'INDEPENDENCIA', 'estado_id' => 17],
            ['nombre' => 'LANDER', 'estado_id' => 17],
            ['nombre' => 'LOS SALIAS', 'estado_id' => 17],
            ['nombre' => 'PÁEZ', 'estado_id' => 17],
            ['nombre' => 'PAZ CASTILLO', 'estado_id' => 17],
            ['nombre' => 'PEDRO GUAL', 'estado_id' => 17],
            ['nombre' => 'PLAZA', 'estado_id' => 17],
            ['nombre' => 'SIMÓN BOLÍVAR', 'estado_id' => 17],
            ['nombre' => 'URDANETA', 'estado_id' => 17],
            ['nombre' => 'SUCRE', 'estado_id' => 17],
            ['nombre' => 'ZAMORA', 'estado_id' => 17],
            //Monagas
            ['nombre' => 'ACOSTA', 'estado_id' => 18],
            ['nombre' => 'AGUASAY', 'estado_id' => 18],
            ['nombre' => 'BOLÍVAR', 'estado_id' => 18],
            ['nombre' => 'CARIPE', 'estado_id' => 18],
            ['nombre' => 'CEDEÑO', 'estado_id' => 18],
            ['nombre' => 'EZEQUIEL ZAMORA', 'estado_id' => 18],
            ['nombre' => 'LIBERTADOR', 'estado_id' => 18],
            ['nombre' => 'MATURÍN', 'estado_id' => 18],
            ['nombre' => 'PIAR', 'estado_id' => 18],
            ['nombre' => 'PUNCERES', 'estado_id' => 18],
            ['nombre' => 'SANTA BÁRBARA', 'estado_id' => 18],
            ['nombre' => 'SOTILLO', 'estado_id' => 18],
            ['nombre' => 'URACOA', 'estado_id' => 18],
            //Nueva Esparta
            ['nombre' => 'ANTOLÍN DEL CAMPO', 'estado_id' => 19],
            ['nombre' => 'ARISMENDI', 'estado_id' => 19],
            ['nombre' => 'DÍAZ', 'estado_id' => 19],
            ['nombre' => 'GARCÍA', 'estado_id' => 19],
            ['nombre' => 'GÓMEZ', 'estado_id' => 19],
            ['nombre' => 'MANEIRO', 'estado_id' => 19],
            ['nombre' => 'MARCANO', 'estado_id' => 19],
            ['nombre' => 'MARIÑO', 'estado_id' => 19],
            ['nombre' => 'MACANAO', 'estado_id' => 19],
            ['nombre' => 'TUBORES', 'estado_id' => 19],
            ['nombre' => 'VILLALBA', 'estado_id' => 19],
            //Portuguesa
            ['nombre' => 'AGUA BLANCA', 'estado_id' => 20],
            ['nombre' => 'ARAURE', 'estado_id' => 20],
            ['nombre' => 'ESTELLER', 'estado_id' => 20],
            ['nombre' => 'GUANARE', 'estado_id' => 20],
            ['nombre' => 'GUANARITO', 'estado_id' => 20],
            ['nombre' => 'MONSEÑOR JOSÉ VICENTE DE UNDA', 'estado_id' => 20],
            ['nombre' => 'OSPINO', 'estado_id' => 20],
            ['nombre' => 'PÁEZ', 'estado_id' => 20],
            ['nombre' => 'PAPELÓN', 'estado_id' => 20],
            ['nombre' => 'SAN GENARO DE BOCONOÍTO', 'estado_id' => 20],
            ['nombre' => 'SAN RAFAEL DE ONOTO', 'estado_id' => 20],
            ['nombre' => 'SANTA ROSALÍA', 'estado_id' => 20],
            ['nombre' => 'SUCRE', 'estado_id' => 20],
            ['nombre' => 'TURÉN', 'estado_id' => 20],
            //Sucre
            ['nombre' => 'ANDRÉSELOY BLANCO', 'estado_id' => 21],
            ['nombre' => 'ANDRÉS MATA', 'estado_id' => 21],
            ['nombre' => 'ARISMENDI', 'estado_id' => 21],
            ['nombre' => 'BENÍTEZ', 'estado_id' => 21],
            ['nombre' => 'BERMÚDEZ', 'estado_id' => 21],
            ['nombre' => 'BOLÍVAR', 'estado_id' => 21],
            ['nombre' => 'CAJIGAL', 'estado_id' => 21],
            ['nombre' => 'CRUZ SALMERÓN ACOSTA', 'estado_id' => 21],
            ['nombre' => 'LIBERTADOR', 'estado_id' => 21],
            ['nombre' => 'MARIÑO', 'estado_id' => 21],
            ['nombre' => 'MEJÍA', 'estado_id' => 21],
            ['nombre' => 'MONTES', 'estado_id' => 21],
            ['nombre' => 'RIBERO', 'estado_id' => 21],
            ['nombre' => 'SUCRE', 'estado_id' => 21],
            ['nombre' => 'VALDEZ', 'estado_id' => 21],
            //Táchira
            ['nombre' => 'ANDRÉS BELLO', 'estado_id' => 22],
            ['nombre' => 'ANTONIO RÓMULO COSTA', 'estado_id' => 22],
            ['nombre' => 'AYACUCHO', 'estado_id' => 22],
            ['nombre' => 'BOLÍVAR', 'estado_id' => 22],
            ['nombre' => 'CÁRDENAS', 'estado_id' => 22],
            ['nombre' => 'CÓRDOBA', 'estado_id' => 22],
            ['nombre' => 'FERNÁNDEZ FEO', 'estado_id' => 22],
            ['nombre' => 'FRANCISCO DE MIRANDA', 'estado_id' => 22],
            ['nombre' => 'GARCÍA DE HEVIA', 'estado_id' => 22],
            ['nombre' => 'GUÁSIMOS', 'estado_id' => 22],
            ['nombre' => 'INDEPENDENCIA', 'estado_id' => 22],
            ['nombre' => 'JÁUREGUI', 'estado_id' => 22],
            ['nombre' => 'JOSÉ MARÍA VARGAS', 'estado_id' => 22],
            ['nombre' => 'JUNÍN', 'estado_id' => 22],
            ['nombre' => 'LIBERTAD', 'estado_id' => 22],
            ['nombre' => 'LIBERTADOR', 'estado_id' => 22],
            ['nombre' => 'LOBATERA', 'estado_id' => 22],
            ['nombre' => 'MICHELENA', 'estado_id' => 22],
            ['nombre' => 'PANAMERICANO', 'estado_id' => 22],
            ['nombre' => 'PEDRO MARÍA UREÑA', 'estado_id' => 22],
            ['nombre' => 'RAFAEL URDANETA', 'estado_id' => 22],
            ['nombre' => 'SAMUEL DARÍO MALDONADO', 'estado_id' => 22],
            ['nombre' => 'SAN CRISTÓBAL', 'estado_id' => 22],
            ['nombre' => 'SEBORUCO', 'estado_id' => 22],
            ['nombre' => 'SIMÓN RODRÍGUEZ', 'estado_id' => 22],
            ['nombre' => 'SUCRE', 'estado_id' => 22],
            ['nombre' => 'TORBES', 'estado_id' => 22],
            ['nombre' => 'URIBANTE', 'estado_id' => 22],
            ['nombre' => 'SAN JUDAS TADEO', 'estado_id' => 22],
            //Trujillo
            ['nombre' => 'ANDRÉS BELLO', 'estado_id' => 23],
            ['nombre' => 'BOCONÓ', 'estado_id' => 23],
            ['nombre' => 'BOLÍVAR', 'estado_id' => 23],
            ['nombre' => 'CANDELARIA', 'estado_id' => 23],
            ['nombre' => 'CARACHE', 'estado_id' => 23],
            ['nombre' => 'ESCUQUE', 'estado_id' => 23],
            ['nombre' => 'JOSÉ FELIPE MÁRQUEZ CAÑIZALEZ', 'estado_id' => 23],
            ['nombre' => 'JUAN VICENTE CAMPOSELÍAS', 'estado_id' => 23],
            ['nombre' => 'LA CEIBA', 'estado_id' => 23],
            ['nombre' => 'MIRANDA', 'estado_id' => 23],
            ['nombre' => 'MONTE CARMELO', 'estado_id' => 23],
            ['nombre' => 'MOTATÁN', 'estado_id' => 23],
            ['nombre' => 'PAMPÁN', 'estado_id' => 23],
            ['nombre' => 'PAMPANITO', 'estado_id' => 23],
            ['nombre' => 'RAFAEL RANGEL', 'estado_id' => 23],
            ['nombre' => 'SAN RAFAEL DE CARVAJAL', 'estado_id' => 23],
            ['nombre' => 'SUCRE', 'estado_id' => 23],
            ['nombre' => 'TRUJILLO', 'estado_id' => 23],
            ['nombre' => 'URDANETA', 'estado_id' => 23],
            ['nombre' => 'VALERA', 'estado_id' => 23],
            //Yaracuy
            ['nombre' => 'ARÍSTIDES BASTIDAS', 'estado_id' => 24],
            ['nombre' => 'BOLÍVAR', 'estado_id' => 24],
            ['nombre' => 'BRUZUAL', 'estado_id' => 24],
            ['nombre' => 'COCOROTE', 'estado_id' => 24],
            ['nombre' => 'INDEPENDENCIA', 'estado_id' => 24],
            ['nombre' => 'JOSÉ ANTONIO PÁEZ', 'estado_id' => 24],
            ['nombre' => 'LA TRINIDAD', 'estado_id' => 24],
            ['nombre' => 'MANUEL MONGE', 'estado_id' => 24],
            ['nombre' => 'NIRGUA', 'estado_id' => 24],
            ['nombre' => 'PEÑA', 'estado_id' => 24],
            ['nombre' => 'SAN FELIPE', 'estado_id' => 24],
            ['nombre' => 'SUCRE', 'estado_id' => 24],
            ['nombre' => 'URACHICHE', 'estado_id' => 24],
            ['nombre' => 'JOSÉ JOAQUÍN VEROES', 'estado_id' => 24],
            //Zulia
            ['nombre' => 'ALMIRANTE PADILLA', 'estado_id' => 25],
            ['nombre' => 'BARALT', 'estado_id' => 25],
            ['nombre' => 'CABIMAS', 'estado_id' => 25],
            ['nombre' => 'CATATUMBO', 'estado_id' => 25],
            ['nombre' => 'COLÓN', 'estado_id' => 25],
            ['nombre' => 'FRANCISCO JAVIER PULGAR', 'estado_id' => 25],
            ['nombre' => 'JESÚS ENRIQUE LOSSADA', 'estado_id' => 25],
            ['nombre' => 'JESÚS MARÍA SEMPRÚN', 'estado_id' => 25],
            ['nombre' => 'LA CAÑADA DE URDANETA', 'estado_id' => 25],
            ['nombre' => 'LAGUNILLAS', 'estado_id' => 25],
            ['nombre' => 'MACHIQUES DE PERIJÁ', 'estado_id' => 25],
            ['nombre' => 'MARA', 'estado_id' => 25],
            ['nombre' => 'MARACAIBO', 'estado_id' => 25],
            ['nombre' => 'MIRANDA', 'estado_id' => 25],
            ['nombre' => 'PÁEZ', 'estado_id' => 25],
            ['nombre' => 'ROSARIO DE PERIJÁ', 'estado_id' => 25],
            ['nombre' => 'SAN FRANCISCO', 'estado_id' => 25],
            ['nombre' => 'SANTA RITA', 'estado_id' => 25],
            ['nombre' => 'SIMÓN BOLÍVAR', 'estado_id' => 25],
            ['nombre' => 'SUCRE', 'estado_id' => 25],
            ['nombre' => 'VALMORE RODRÍGUEZ', 'estado_id' => 25],
            
        ];

        DB::table('municipios')->insert($municipios);
    }
}
